services:
  service:
    env_file: .env
    build:
      dockerfile: Dockerfile
      target: development
    expose:
      - 80
    healthcheck:
      test: curl --fail http://localhost/actuator/health || exit 1
      interval: 20s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - 5001:5001 # dt_socket for Java Debug Attach
    tty: true
    volumes:
      - ./:/home/appuser/app
      - ${HOME}/.m2/repository:/home/appuser/.m2/repository

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./local/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres:
