name: NPS Setup Java

description: Setup Java, Maven, cache, and GitHub Packages configuration

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
